import { LayoutProviders } from '@/components/LayoutProviders'
import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className='bg-background'>
        <NextTopLoader
          color="#2299DD"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="ease"
          speed={200}
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"
        />
        <main className='relative min-h-screen'>
          <LayoutProviders>
            {children}
          </LayoutProviders>
        </main>
      </body>
    </html>
  )
}
